version: "3"
services:
    mongodb:
        image: mongo
        expose:
            - "27017"
        ports:
            - "27017:27017"
        deploy:
            resources:
                limits:
                    memory: 512MB
                reservations:
                    memory: 512MB   
        networks:
            - default
        container_name: mongodb-shopstyle
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: 12345
    rabbitmq:
        image: rabbitmq:management
        expose:
         - "5672"
        ports:
         - "15672:15672"
         - "5672:5672"
        deploy:
            resources:
                limits:
                    memory: 256MB
                reservations:
                    memory: 256MB
        networks:
          - default
        volumes:
          - ./rabbitmq:/var/lib/rabbitmq/
        container_name: rabbitmq-shopstyle
        restart: always
    zookeeper:
        image: confluentinc/cp-zookeeper:5.2.1
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
          ZOOKEEPER_SYNC_LIMIT: 2
        ports:
          - "2181:2181"
        container_name: zookeper-shopstyle
    kafka:
        image: confluentinc/cp-kafka:5.2.1
        ports:
          - "9092:9092"
        depends_on:
          - zookeeper
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        container_name: kafka-shopstyle